// Generated by chipseq - "Demo Mono" @ 180 BPM, 4/4
// Requires "pitches.h"
#pragma once

#ifndef NOTE_REST
#define NOTE_REST 0
#endif

static const BadgeNote DEMO_MONO[] = {
  {NOTE_C4     ,   83}, {NOTE_E4     ,   84}, {NOTE_G4     ,   83}, {NOTE_C5     ,   83}, {NOTE_E5     ,   84}, {NOTE_G5     ,   83}, {NOTE_E5     ,   83}, {NOTE_C5     ,   84},
  {NOTE_GS3    ,   83}, {NOTE_C4     ,   83}, {NOTE_DS4    ,   84}, {NOTE_GS4    ,   83}, {NOTE_C5     ,   83}, {NOTE_DS5    ,   84}, {NOTE_C5     ,   83}, {NOTE_GS4    ,   83},
  {NOTE_AS4    ,   84}, {NOTE_D5     ,   83}, {NOTE_F5     ,   83}, {NOTE_AS5    ,   84}, {NOTE_D6     ,   83}, {NOTE_F6     ,   83}, {NOTE_D6     ,   84}, {NOTE_AS5    ,   83},
  {NOTE_C4     ,   83}, {NOTE_E4     ,   84}, {NOTE_C4     ,   83}, {NOTE_C6     ,  417},
};
static const int DEMO_MONO_LEN = sizeof(DEMO_MONO) / sizeof(DEMO_MONO[0]);
