// .h exporter: mono flattened events -> Arduino-style BadgeNote array.

import { flattenSong, clipEventsToRegion } from './flatten.js';
import { PITCH_SYMBOLS } from './music.js';

// MIDI 60 -> NOTE_C4 (Arduino pitches.h octave numbering).
export function pitchSymbol(pitch) {
  return 'NOTE_' + PITCH_SYMBOLS[pitch % 12] + (Math.floor(pitch / 12) - 1);
}

export function sanitizeSymbolName(name) {
  let s = (name || 'TUNE')
    .toUpperCase()
    .replace(/[^A-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
  if (!s) s = 'TUNE';
  if (/^[0-9]/.test(s)) s = 'T_' + s;
  return s;
}

// pitches.h ships NOTE_B0 (MIDI 23) .. NOTE_DS8 (MIDI 111).
const PITCHES_H_MIN = 23;
const PITCHES_H_MAX = 111;

// opts.region: {startTick, endTick} — export only that slice, rebased to 0.
// Region exports keep leading/trailing rests so the total length is exactly
// the region length (important for seamless loops on the badge).
export function exportHeader(doc, symbolName, opts = {}) {
  let { events, warnings: flatWarnings } = flattenSong(doc);
  const region = opts.region && opts.region.endTick > opts.region.startTick ? opts.region : null;
  if (region) events = clipEventsToRegion(events, region.startTick, region.endTick);
  const warnings = flatWarnings.map((w) =>
    w.type === 'overlap'
      ? 'Overlapping notes were truncated (fix conflicts for exact control).'
      : 'A chord decoration was exported as its plain root note (chords are not available in mono).'
  );

  const msPerTick = 60000 / (doc.song.bpm * doc.ppq);
  const name = sanitizeSymbolName(symbolName || doc.name);

  // Build {symbol, ms} entries; rests fill internal gaps. Rounding uses
  // absolute boundary times so total duration never drifts.
  const entries = [];
  const outOfRange = new Set();
  // Full export skips leading silence; region export keeps it as a rest.
  let prevEndTick = region || !events.length ? 0 : events[0].startTick;

  const pushEntry = (symbol, startTick, endTick) => {
    const ms = Math.round(endTick * msPerTick) - Math.round(startTick * msPerTick);
    if (ms <= 0) return;
    entries.push({ symbol, ms });
  };

  for (const ev of events) {
    if (ev.startTick > prevEndTick) pushEntry('NOTE_REST', prevEndTick, ev.startTick);
    if (ev.pitch < PITCHES_H_MIN || ev.pitch > PITCHES_H_MAX) outOfRange.add(pitchSymbol(ev.pitch));
    pushEntry(pitchSymbol(ev.pitch), ev.startTick, ev.startTick + ev.durationTicks);
    prevEndTick = ev.startTick + ev.durationTicks;
  }
  if (region) {
    const regionTicks = region.endTick - region.startTick;
    if (regionTicks > prevEndTick) pushEntry('NOTE_REST', prevEndTick, regionTicks);
  }

  if (outOfRange.size) {
    warnings.push(
      `Notes outside pitches.h range (B0..DS8): ${[...outOfRange].join(', ')} — define them yourself or transpose.`
    );
  }

  const lines = [];
  lines.push(`// Generated by chipseq — "${doc.name}" @ ${doc.song.bpm} BPM, ${doc.song.timeSig.num}/${doc.song.timeSig.den}${region ? ' (loop region)' : ''}`);
  lines.push('// Requires "pitches.h"');
  lines.push('#pragma once');
  lines.push('');
  lines.push('#ifndef NOTE_REST');
  lines.push('#define NOTE_REST 0');
  lines.push('#endif');
  lines.push('');
  lines.push(`static const BadgeNote ${name}[] = {`);
  for (let i = 0; i < entries.length; i += 8) {
    const chunk = entries
      .slice(i, i + 8)
      .map((e) => `{${e.symbol.padEnd(12)}, ${String(e.ms).padStart(4)}}`)
      .join(', ');
    lines.push('  ' + chunk + ',');
  }
  lines.push('};');
  lines.push(`static const int ${name}_LEN = sizeof(${name}) / sizeof(${name}[0]);`);
  lines.push('');

  return { text: lines.join('\n'), warnings, entryCount: entries.length, name };
}
