// Service worker: ChipSeq as an installed app that works with no network.
//
// The app already had everything it needs to run offline - no CDN, no fonts,
// no API, and localStorage for projects. The only thing standing between that
// and an app you can open on a rebooted laptop in a field was the browser
// having to fetch the files. This caches them.
//
// Three decisions, and each one exists to avoid a specific way this goes wrong:
//
// 1. THE FILE LIST IS GENERATED, NOT WRITTEN. `node tools/gen-precache.mjs`
//    walks index.html and the real import graph and rewrites the block below;
//    tests/unit.mjs fails if the committed block is stale. A hand-kept list
//    rots - tests/check.mjs kept one for a year and quietly lost two modules -
//    and a rotted list here means a module that is missing only when offline,
//    which is the worst time to find out.
//
// 2. AN UPDATE NEVER ACTIVATES BY ITSELF. A new version installs in the
//    background and then waits. The page asks for it (status bar, "update
//    ready - reload"). Swapping caches under a running editor would let a page
//    dynamic-import a tool module - they carry ?v=APP_VERSION - out of a cache
//    written by a different build, and would also throw away unsaved work
//    without asking.
//
// 3. INSTALLING REUSES WHAT DID NOT CHANGE. Each entry carries a content hash,
//    so a release copies the untouched files across from the previous cache and
//    fetches only what actually differs. Without it every release would pull
//    the whole app again - measured at 2.4 MB, most of it demo songs - in the
//    background, on whatever connection the venue has.

const CACHE_PREFIX = 'chipseq-';

// ---- GENERATED by tools/gen-precache.mjs - do not edit by hand ----
const VERSION = '0.8.0';
const ASSETS = [
  ['assets/icon-192.png', '9eba2c0aafbe'],
  ['assets/icon-512.png', '939ad6831994'],
  ['assets/icon-maskable-512.png', '06b1bfa9264c'],
  ['assets/icons.svg', 'fe32bf06c573'],
  ['css/base.css', '64ffa79c7c4e'],
  ['css/components.css', '3cba136136d6'],
  ['css/layout.css', '8d0fc07fa427'],
  ['demos/bad-apple.chipseq.json', '4c9294354c97'],
  ['demos/index.json', '218005f94989'],
  ['demos/mono.chipseq.json', 'dd266ddb4000'],
  ['demos/poly.chipseq.json', '16329facce87'],
  ['demos/rickroll.chipseq.json', '640c2b3a00fb'],
  ['demos/tetris.chipseq.json', 'c3d38a4db6c0'],
  ['demos/unreal-superhero-3.chipseq.json', '7e63bb56bfb5'],
  ['index.html', 'deae8a30bd11'],
  ['js/core/automation.js', 'c810d43e467c'],
  ['js/core/badge-import.js', 'ca2545a03740'],
  ['js/core/badge-score.js', 'ae86459e6497'],
  ['js/core/badge-tune.js', '2fbf0fd473f7'],
  ['js/core/doc.js', 'f3af80ee894c'],
  ['js/core/effects.js', '4281f68dd82d'],
  ['js/core/engine.js', '978083f70ec2'],
  ['js/core/export-fmf.js', 'aa306289f216'],
  ['js/core/export-h.js', '47b002a06dd6'],
  ['js/core/export-wav.js', '374d8e8b1094'],
  ['js/core/exporters.js', '245b4620f0ec'],
  ['js/core/flatten.js', 'ccf1422d5a7b'],
  ['js/core/graph.js', '9bd5ebffb5df'],
  ['js/core/harmonics.js', 'bb6e09c1df79'],
  ['js/core/history.js', '913ddc267186'],
  ['js/core/instruments.js', '0ff006a2fc07'],
  ['js/core/midi-import.js', 'd7fc5af125b1'],
  ['js/core/modulation.js', 'cb28ea65f453'],
  ['js/core/music.js', '07756a674f20'],
  ['js/core/normalize.js', '3da340c77122'],
  ['js/core/persist.js', '4512694968c9'],
  ['js/core/store.js', '890fb86a9f81'],
  ['js/core/units.js', '0e9a2e51b9ef'],
  ['js/core/version.js', '428b75abb920'],
  ['js/main.js', '9375fa077f3c'],
  ['js/net/badge-stream.js', 'c1bf8cae2c2b'],
  ['js/net/badge-upload.js', '8dfc58d55471'],
  ['js/net/badges.js', '1218e0609971'],
  ['js/ui/commands.js', 'fb9c12241f91'],
  ['js/ui/conflicts.js', 'bf7e852b208b'],
  ['js/ui/dialogs.js', '47cc9202dc1a'],
  ['js/ui/export-dialog.js', '6c15e6749e14'],
  ['js/ui/icons.js', '71831d48270e'],
  ['js/ui/keymap.js', '3d68fedb0052'],
  ['js/ui/midi-import-dialog.js', 'feb57328cfc1'],
  ['js/ui/offline.js', '5eec32dfd562'],
  ['js/ui/palette.js', '7165153bfabb'],
  ['js/ui/panel-resize.js', 'ccb451369987'],
  ['js/ui/piano-roll/automation-lane.js', 'f2e15825e67f'],
  ['js/ui/piano-roll/coords.js', '94c6d187ed21'],
  ['js/ui/piano-roll/interactions.js', 'd5244f87b2dc'],
  ['js/ui/piano-roll/piano-roll.js', '401a5b66f0db'],
  ['js/ui/piano-roll/render.js', '0683ca6001c8'],
  ['js/ui/start-screen.js', 'd5c670094875'],
  ['js/ui/status-bar.js', '714d2f0a4a7c'],
  ['js/ui/toolbar.js', '59f231c1cec0'],
  ['js/ui/tools-panel.js', '305409d02558'],
  ['js/ui/tools/badges.js', '846bed318eda'],
  ['js/ui/tools/effects.js', '84d1f1a4c3c9'],
  ['js/ui/tools/envelope-editor.js', '8ae27ecfdc03'],
  ['js/ui/tools/harmonics.js', '0c2488e2b9c6'],
  ['js/ui/tools/instrument.js', 'e73f315c5156'],
  ['js/ui/tools/levels.js', '004285d46985'],
  ['js/ui/tools/manifest.js', 'a54652390621'],
  ['js/ui/tools/mixer.js', '762948430741'],
  ['js/ui/tools/transpose.js', 'ef9c0f4424f5'],
  ['js/ui/tracks-panel.js', 'c3862788bc78'],
  ['js/ui/trimmer.js', '72bd03e6c600'],
  ['js/ui/ui-store.js', 'a6f1bb604f03'],
  ['manifest.webmanifest', 'd6f0455b7853'],
];
// ---- END GENERATED ----

const CACHE = CACHE_PREFIX + VERSION;

// Absolute, and resolved against the worker's own location, so the same file
// works at /ChipSeq/ on Pages and at / on the badge server.
const href = (path) => new URL(path, self.location).href;

// The previous install's file list, kept inside the cache it describes. Not a
// real path - nothing is ever served from it - it just needs a key that no
// asset can collide with.
const MANIFEST_KEY = href('sw-manifest.json');

// Six at a time. Seventy parallel fetches is a burst a phone tether does not
// enjoy, and doing them one at a time would spend a minute of round trips over
// a relayed connection.
const PARALLEL = 6;

async function pool(items, worker) {
  const queue = items.slice();
  const runners = [];
  for (let i = 0; i < Math.min(PARALLEL, queue.length); i++) {
    runners.push(
      (async () => {
        while (queue.length) await worker(queue.shift());
      })()
    );
  }
  await Promise.all(runners);
}

// ---- install ----

self.addEventListener('install', (event) => event.waitUntil(precache()));

async function precache() {
  const cache = await caches.open(CACHE);
  const previous = await previousCache();
  const known = await previousHashes(previous);

  await pool(ASSETS, async ([path, hash]) => {
    const url = href(path);
    if (previous && known.get(path) === hash) {
      const kept = await previous.match(url);
      if (kept) {
        await cache.put(url, kept);
        return;
      }
    }
    // `reload` so a precache never inherits something stale from the HTTP
    // cache: this copy is the one the app runs from until the next release.
    //
    // Bounded for the same reason the fetch handler is: a single request that
    // never settles would leave this worker in `installing` for as long as the
    // browser allows, and a worker stuck installing is one that can never be
    // updated either. Failing the install is recoverable - the next visit
    // tries again - while hanging is not.
    const res = await deadline(fetch(url, { cache: 'reload' }), NET_DEADLINE_MS, null);
    if (!res) throw new Error(`precache timed out: ${path}`);
    if (!res.ok) throw new Error(`precache failed: ${path} (${res.status})`);
    await cache.put(url, res);
  });

  await cache.put(
    MANIFEST_KEY,
    new Response(JSON.stringify(ASSETS), { headers: { 'Content-Type': 'application/json' } })
  );
  // Deliberately no skipWaiting() - see (2) above.
}

// caches.keys() is in creation order, so the last one that is not ours is the
// build we are replacing.
async function previousCache() {
  const names = (await caches.keys()).filter((n) => n.startsWith(CACHE_PREFIX) && n !== CACHE);
  return names.length ? await caches.open(names[names.length - 1]) : null;
}

async function previousHashes(previous) {
  if (!previous) return new Map();
  try {
    const res = await previous.match(MANIFEST_KEY);
    if (!res) return new Map();
    return new Map(await res.json());
  } catch {
    return new Map(); // an unreadable manifest just means fetching everything
  }
}

// ---- activate ----

self.addEventListener('activate', (event) => event.waitUntil(takeOver()));

async function takeOver() {
  for (const name of await caches.keys()) {
    if (name.startsWith(CACHE_PREFIX) && name !== CACHE) await caches.delete(name);
  }
  await self.clients.claim();
}

// ---- fetch ----
//
// 4. NOTHING HERE MAY WAIT FOREVER. Once this worker calls respondWith, the
//    browser waits on OUR promise, and a navigation that never resolves is a
//    blank page - for about five minutes, which is when Chromium gives up on
//    a service worker event and goes to the network itself. That is not a
//    theory: a navigation was observed pending for 397 seconds with the
//    renderer perfectly responsive, so the page had simply never been
//    answered. Whatever put the worker in that state, the worker must not be
//    able to hold a page hostage while it is there - so every path below is
//    bounded, and the bound falls back to the thing most likely to work
//    rather than to an error.

// Long enough that a slow phone on a bad connection still gets its answer
// from the network, short enough that a person does not conclude the app is
// broken and close the tab.
const NET_DEADLINE_MS = 10000;
// The cache lives on disk and is normally instant. If it is not answering
// quickly, waiting longer is not going to help a page that is already blank.
const CACHE_DEADLINE_MS = 3000;

function deadline(promise, ms, fallback) {
  return Promise.race([
    // A rejection is a real answer - let it through rather than converting it
    // into the fallback, or an offline miss would wait the full timeout.
    promise,
    new Promise((resolve) => setTimeout(() => resolve(fallback), ms)),
  ]);
}

// Cache lookups, bounded. A miss and a stall look the same to the caller
// (both null), which is right: in both cases the network is what is left.
async function cacheLookup(cache, req, opts) {
  try {
    return (await deadline(cache.match(req, opts), CACHE_DEADLINE_MS, null)) || null;
  } catch {
    return null; // an unreadable cache is a miss, not a failure to serve
  }
}

async function openCache() {
  try {
    return await deadline(caches.open(CACHE), CACHE_DEADLINE_MS, null);
  } catch {
    return null;
  }
}

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  let sameOrigin = false;
  try {
    sameOrigin = new URL(req.url).origin === self.location.origin;
  } catch {
    return; // an unparseable URL is not ours to serve
  }
  if (!sameOrigin) return;
  // The badge relay is another origin and its socket is not a fetch at all, so
  // nothing about the badge path passes through here.
  //
  // Handing respondWith a rejected promise shows the browser's own network
  // error, which is the honest outcome when neither cache nor network can
  // answer - and far better than never resolving.
  event.respondWith(req.mode === 'navigate' ? shell(req) : cacheFirst(req));
});

// Cache-first, not network-first: freshness comes from the worker updating, so
// revalidating on every request would only add latency and would make an
// offline load wait for a timeout before it worked.
async function cacheFirst(req) {
  const cache = await openCache();
  // ignoreSearch because the lazily loaded tool cards import with
  // ?v=APP_VERSION and the precached key has no query.
  const hit = cache && (await cacheLookup(cache, req, { ignoreSearch: true }));
  return hit || fetch(req);
}

// Any navigation inside the scope is the app, so a reload of a deep URL works
// with no network instead of hitting the server's 404.
async function shell(req) {
  const cache = await openCache();
  const cached = cache && (await cacheLookup(cache, href('index.html')));
  if (cached) return cached;
  // No cached shell: go to the network, but do not wait on it indefinitely.
  // If the deadline passes, try the cache once more - a precache finishing in
  // the background is the likeliest reason both were empty a moment ago - and
  // otherwise let the request fail so the browser reports it.
  const res = await deadline(fetch(req).catch(() => null), NET_DEADLINE_MS, null);
  if (res) return res;
  const late = cache && (await cacheLookup(cache, href('index.html')));
  if (late) return late;
  return Response.error();
}

// ---- messages ----

self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'skip-waiting') self.skipWaiting();
  if (data.type === 'version' && event.ports[0]) event.ports[0].postMessage(VERSION);
});
