// Service worker: ChipSeq as an installed app that works with no network.
//
// The app already had everything it needs to run offline - no CDN, no fonts,
// no API, and localStorage for projects. The only thing standing between that
// and an app you can open on a rebooted laptop in a field was the browser
// having to fetch the files. This caches them.
//
// Three decisions, and each one exists to avoid a specific way this goes wrong:
//
// 1. THE FILE LIST IS GENERATED, NOT WRITTEN. `node tools/gen-precache.mjs`
//    walks index.html and the real import graph and rewrites the block below;
//    tests/unit.mjs fails if the committed block is stale. A hand-kept list
//    rots - tests/check.mjs kept one for a year and quietly lost two modules -
//    and a rotted list here means a module that is missing only when offline,
//    which is the worst time to find out.
//
// 2. AN UPDATE NEVER ACTIVATES BY ITSELF. A new version installs in the
//    background and then waits. The page asks for it (status bar, "update
//    ready - reload"). Swapping caches under a running editor would let a page
//    dynamic-import a tool module - they carry ?v=APP_VERSION - out of a cache
//    written by a different build, and would also throw away unsaved work
//    without asking.
//
// 3. INSTALLING REUSES WHAT DID NOT CHANGE. Each entry carries a content hash,
//    so a release copies the untouched files across from the previous cache and
//    fetches only what actually differs. Without it every release would pull
//    the whole app again - measured at 2.4 MB, most of it demo songs - in the
//    background, on whatever connection the venue has.

const CACHE_PREFIX = 'chipseq-';

// ---- GENERATED by tools/gen-precache.mjs - do not edit by hand ----
const VERSION = '0.7.3';
const ASSETS = [
  ['assets/icon-192.png', '9eba2c0aafbe'],
  ['assets/icon-512.png', '939ad6831994'],
  ['assets/icon-maskable-512.png', '06b1bfa9264c'],
  ['assets/icons.svg', 'fe32bf06c573'],
  ['css/base.css', '64ffa79c7c4e'],
  ['css/components.css', 'd0dd9a959323'],
  ['css/layout.css', '8d0fc07fa427'],
  ['demos/bad-apple.chipseq.json', '4c9294354c97'],
  ['demos/index.json', 'd0dfa6a9dd67'],
  ['demos/mono.chipseq.json', 'dd266ddb4000'],
  ['demos/poly.chipseq.json', '16329facce87'],
  ['demos/rickroll.chipseq.json', '640c2b3a00fb'],
  ['demos/tetris.chipseq.json', 'c3d38a4db6c0'],
  ['index.html', '1c0490063db3'],
  ['js/core/automation.js', 'c810d43e467c'],
  ['js/core/badge-score.js', 'ae86459e6497'],
  ['js/core/badge-tune.js', '2fbf0fd473f7'],
  ['js/core/doc.js', 'fd03b0b865ed'],
  ['js/core/effects.js', '4281f68dd82d'],
  ['js/core/engine.js', '9b280249532d'],
  ['js/core/export-fmf.js', 'aa306289f216'],
  ['js/core/export-h.js', '47b002a06dd6'],
  ['js/core/export-wav.js', '374d8e8b1094'],
  ['js/core/exporters.js', '245b4620f0ec'],
  ['js/core/flatten.js', '914ed8b20310'],
  ['js/core/graph.js', '9bd5ebffb5df'],
  ['js/core/harmonics.js', 'bb6e09c1df79'],
  ['js/core/instruments.js', '0ff006a2fc07'],
  ['js/core/midi-import.js', 'd7fc5af125b1'],
  ['js/core/modulation.js', 'cb28ea65f453'],
  ['js/core/music.js', '07756a674f20'],
  ['js/core/normalize.js', '3da340c77122'],
  ['js/core/persist.js', '4512694968c9'],
  ['js/core/store.js', '244689a06ee8'],
  ['js/core/units.js', '0e9a2e51b9ef'],
  ['js/core/version.js', '32761661975b'],
  ['js/main.js', '1d6d824d00ac'],
  ['js/net/badge-stream.js', 'c1bf8cae2c2b'],
  ['js/net/badge-upload.js', 'ffb80485e486'],
  ['js/net/badges.js', '2cd71764a146'],
  ['js/ui/commands.js', '71e282973ebf'],
  ['js/ui/conflicts.js', 'bf7e852b208b'],
  ['js/ui/dialogs.js', '47cc9202dc1a'],
  ['js/ui/export-dialog.js', '985aa25807f6'],
  ['js/ui/icons.js', '71831d48270e'],
  ['js/ui/keymap.js', '0b379e629097'],
  ['js/ui/midi-import-dialog.js', 'feb57328cfc1'],
  ['js/ui/offline.js', '5eec32dfd562'],
  ['js/ui/palette.js', '7165153bfabb'],
  ['js/ui/panel-resize.js', 'ccb451369987'],
  ['js/ui/piano-roll/automation-lane.js', 'b2085c87fc8c'],
  ['js/ui/piano-roll/coords.js', '94c6d187ed21'],
  ['js/ui/piano-roll/interactions.js', 'd5244f87b2dc'],
  ['js/ui/piano-roll/piano-roll.js', '8953ed43212a'],
  ['js/ui/piano-roll/render.js', '0683ca6001c8'],
  ['js/ui/start-screen.js', 'd5c670094875'],
  ['js/ui/status-bar.js', '714d2f0a4a7c'],
  ['js/ui/toolbar.js', '59f231c1cec0'],
  ['js/ui/tools-panel.js', '305409d02558'],
  ['js/ui/tools/badges.js', 'fe7cfb6f84e6'],
  ['js/ui/tools/effects.js', '84d1f1a4c3c9'],
  ['js/ui/tools/envelope-editor.js', '8ae27ecfdc03'],
  ['js/ui/tools/harmonics.js', '0c2488e2b9c6'],
  ['js/ui/tools/instrument.js', 'e73f315c5156'],
  ['js/ui/tools/levels.js', '004285d46985'],
  ['js/ui/tools/manifest.js', 'a54652390621'],
  ['js/ui/tools/mixer.js', '762948430741'],
  ['js/ui/tools/transpose.js', 'ef9c0f4424f5'],
  ['js/ui/tracks-panel.js', 'dfb9ccf620d8'],
  ['js/ui/trimmer.js', '72bd03e6c600'],
  ['js/ui/ui-store.js', 'a20a5ab084a8'],
  ['manifest.webmanifest', 'd6f0455b7853'],
];
// ---- END GENERATED ----

const CACHE = CACHE_PREFIX + VERSION;

// Absolute, and resolved against the worker's own location, so the same file
// works at /ChipSeq/ on Pages and at / on the badge server.
const href = (path) => new URL(path, self.location).href;

// The previous install's file list, kept inside the cache it describes. Not a
// real path - nothing is ever served from it - it just needs a key that no
// asset can collide with.
const MANIFEST_KEY = href('sw-manifest.json');

// Six at a time. Seventy parallel fetches is a burst a phone tether does not
// enjoy, and doing them one at a time would spend a minute of round trips over
// a relayed connection.
const PARALLEL = 6;

async function pool(items, worker) {
  const queue = items.slice();
  const runners = [];
  for (let i = 0; i < Math.min(PARALLEL, queue.length); i++) {
    runners.push(
      (async () => {
        while (queue.length) await worker(queue.shift());
      })()
    );
  }
  await Promise.all(runners);
}

// ---- install ----

self.addEventListener('install', (event) => event.waitUntil(precache()));

async function precache() {
  const cache = await caches.open(CACHE);
  const previous = await previousCache();
  const known = await previousHashes(previous);

  await pool(ASSETS, async ([path, hash]) => {
    const url = href(path);
    if (previous && known.get(path) === hash) {
      const kept = await previous.match(url);
      if (kept) {
        await cache.put(url, kept);
        return;
      }
    }
    // `reload` so a precache never inherits something stale from the HTTP
    // cache: this copy is the one the app runs from until the next release.
    const res = await fetch(url, { cache: 'reload' });
    if (!res.ok) throw new Error(`precache failed: ${path} (${res.status})`);
    await cache.put(url, res);
  });

  await cache.put(
    MANIFEST_KEY,
    new Response(JSON.stringify(ASSETS), { headers: { 'Content-Type': 'application/json' } })
  );
  // Deliberately no skipWaiting() - see (2) above.
}

// caches.keys() is in creation order, so the last one that is not ours is the
// build we are replacing.
async function previousCache() {
  const names = (await caches.keys()).filter((n) => n.startsWith(CACHE_PREFIX) && n !== CACHE);
  return names.length ? await caches.open(names[names.length - 1]) : null;
}

async function previousHashes(previous) {
  if (!previous) return new Map();
  try {
    const res = await previous.match(MANIFEST_KEY);
    if (!res) return new Map();
    return new Map(await res.json());
  } catch {
    return new Map(); // an unreadable manifest just means fetching everything
  }
}

// ---- activate ----

self.addEventListener('activate', (event) => event.waitUntil(takeOver()));

async function takeOver() {
  for (const name of await caches.keys()) {
    if (name.startsWith(CACHE_PREFIX) && name !== CACHE) await caches.delete(name);
  }
  await self.clients.claim();
}

// ---- fetch ----

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).origin !== self.location.origin) return;
  // The badge relay is another origin and its socket is not a fetch at all, so
  // nothing about the badge path passes through here.
  event.respondWith(req.mode === 'navigate' ? shell(req) : cacheFirst(req));
});

// Cache-first, not network-first: freshness comes from the worker updating, so
// revalidating on every request would only add latency and would make an
// offline load wait for a timeout before it worked.
async function cacheFirst(req) {
  const cache = await caches.open(CACHE);
  // ignoreSearch because the lazily loaded tool cards import with
  // ?v=APP_VERSION and the precached key has no query.
  const hit = await cache.match(req, { ignoreSearch: true });
  return hit || fetch(req);
}

// Any navigation inside the scope is the app, so a reload of a deep URL works
// with no network instead of hitting the server's 404.
async function shell(req) {
  const cache = await caches.open(CACHE);
  return (await cache.match(href('index.html'))) || fetch(req);
}

// ---- messages ----

self.addEventListener('message', (event) => {
  const data = event.data || {};
  if (data.type === 'skip-waiting') self.skipWaiting();
  if (data.type === 'version' && event.ports[0]) event.ports[0].postMessage(VERSION);
});
